name: ci_meson

on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: "Installing dependencies"
      run: sudo apt update && sudo apt install -y pkg-config libsamplerate0-dev libsndfile1-dev libfftw3-dev ladspa-sdk lv2-dev vamp-plugin-sdk libboost-test-dev meson ninja-build
    - name: "Configuring and building linux"
      run: meson build_linux -Dresampler=libsamplerate -Dfft=fftw && ninja -C build_linux
      env:
        CC: gcc
    - name: upload linux logs
      uses: actions/upload-artifact@v1
      with:
        name: Linux_Meson_Testlog
        path: build_linux/meson-logs/meson-log.txt
    - name: upload linux rubberband
      uses: actions/upload-artifact@v1
      with:
        name: Linux_Rubberband
        path: build_linux/

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: brew install gcc libsndfile libsamplerate vamp-plugin-sdk meson ninja
    - name: build macos
      run: meson build_macos -Dresampler=libsamplerate
    - name: build ios
      run: meson build_ios -Dresampler=libsamplerate --cross-file cross/ios.txt
      env:
        CC: gcc
    - name: make macos
      run: ninja -C build_macos
    - name: make ios
      run: ninja -C build_ios
    - name: upload macos logs
      uses: actions/upload-artifact@v1
      with:
        name: MacOS_Meson_Testlog
        path: build_macos/meson-logs/meson-log.txt
    - name: upload macos rubberband
      uses: actions/upload-artifact@v1
      with:
        name: MacOS_Rubberband
        path: build_macos/
    - name: upload ios logs
      uses: actions/upload-artifact@v1
      with:
        name: IOS_Meson_Testlog
        path: build_ios/meson-logs/meson-log.txt
    - name: upload ios rubberband
      uses: actions/upload-artifact@v1
      with:
        name: IOS_Rubberband
        path: build_ios/

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install meson ninja
    - name: configure windows
      run: meson build_windows -Dfft=fftw -Dresampler=libsamplerate
      env:
        CC: gcc
    - name: make windows
      run: ninja -C build_windows
      env:
        CC: gcc
    - name: upload windows logs
      uses: actions/upload-artifact@v1
      with:
        name: Windows_Meson_Testlog
        path: build_windows/meson-logs/meson-log.txt
    - name: upload windows rubberband
      uses: actions/upload-artifact@v1
      with:
        name: Windows_Rubberband
        path: build_windows/


